import { dateKey, addDays } from '../domain/dates';
import type { Activity, AppState, Preferences } from '../domain/types';
export const defaultPreferences: Preferences = {
  name: 'Alex',
  onboarded: false,
  demo: true,
  schedule: 'work',
  wake: '07:00',
  sleep: '23:00',
  workStart: '09:00',
  workEnd: '17:00',
  workDays: [1, 2, 3, 4, 5],
  goals: ['Stay focused', 'Move every day', 'Find balance'],
  theme: 'light',
  intensity: 'gentle',
  notifications: false,
  before: true,
  start: true,
  followUp: false,
  missed: false,
  breaks: true,
  habits: true,
  review: true,
};
export function createInitialState(): AppState {
  const today = dateKey();
  const make = (
    id: string,
    title: string,
    time: string,
    duration: number,
    category: Activity['category'],
    type: Activity['type'] = 'task',
    done = false,
    notes = '',
  ): Activity => ({
    id,
    title,
    time,
    duration,
    category,
    type,
    notes,
    date: today,
    days: [],
    completedOn: done ? [today] : [],
    reminder: true,
    leadMinutes: type === 'meeting' ? 10 : 5,
  });
  const activities = [
    make(
      'water',
      'Wake up & hydrate',
      '07:00',
      15,
      'health',
      'habit',
      true,
      'A glass of water. A fresh beginning.',
    ),
    make(
      'movement',
      'Morning movement',
      '07:15',
      30,
      'health',
      'habit',
      true,
      'Stretch, breathe, and take a short walk.',
    ),
    make(
      'breakfast',
      'Breakfast & a little reading',
      '08:00',
      30,
      'personal',
      'personal',
      true,
      'A slow start, before the busy part.',
    ),
    make(
      'plan',
      'Set intentions for the day',
      '09:00',
      15,
      'work',
      'task',
      true,
      'Choose three things that matter most.',
    ),
    make(
      'deep',
      'Design the next big thing',
      '09:30',
      90,
      'work',
      'focus',
      false,
      'Explore the new brand direction. One idea at a time.',
    ),
    make(
      'break',
      'Step away & recharge',
      '11:00',
      15,
      'rest',
      'personal',
      false,
      'Get some fresh air. Your inbox can wait.',
    ),
    make(
      'meeting',
      'Team check-in',
      '11:30',
      30,
      'work',
      'meeting',
      false,
      'Catch up with Maya and the design team.',
    ),
    make(
      'lunch',
      'Lunch, away from the screen',
      '12:30',
      45,
      'personal',
      'personal',
    ),
    make(
      'study',
      'Learn something new',
      '14:00',
      45,
      'study',
      'task',
      false,
      'A chapter of the interaction design course.',
    ),
    make('walk', 'An evening walk', '18:00', 30, 'health', 'habit'),
    make('review', 'Reflect & wind down', '21:30', 20, 'rest', 'personal'),
    make('sleep', 'Time to unplug', '22:30', 30, 'rest', 'reminder'),
  ];
  activities.push(
    {
      ...make(
        'tomorrow-deep',
        'Bring the concept to life',
        '09:30',
        90,
        'work',
        'focus',
      ),
      date: addDays(today, 1),
    },
    {
      ...make(
        'tomorrow-meeting',
        'Creative review with Maya',
        '11:30',
        45,
        'work',
        'meeting',
      ),
      date: addDays(today, 1),
    },
  );
  return {
    version: 1,
    activities,
    routines: [
      {
        id: 'morning',
        title: 'A mindful morning',
        days: [1, 2, 3, 4, 5],
        enabled: false,
        steps: [
          {
            id: 'water',
            title: 'Wake up & drink water',
            time: '07:00',
            duration: 15,
            category: 'health',
          },
          {
            id: 'move',
            title: 'A little movement',
            time: '07:15',
            duration: 30,
            category: 'health',
          },
          {
            id: 'meal',
            title: 'Breakfast',
            time: '08:00',
            duration: 30,
            category: 'personal',
          },
        ],
      },
    ],
    preferences: { ...defaultPreferences },
    focus: null,
    sessions: [
      {
        id: 'sample-focus',
        date: today,
        title: 'Set intentions for the day',
        seconds: 1500,
      },
    ],
    reviews: {},
  };
}
